package ir.atlassian.jira.plugins.security;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.lang.reflect.Field;
import java.lang.reflect.Method;

import static org.junit.Assert.*;

/**
 * Unit tests for {@link IntegrityChecker}.
 * <p>
 * This class uses Java Reflection to test private methods and manipulate
 * static state (e.g., cached verification results) ensuring thorough coverage
 * of the plugin's self-verification and security mechanics.
 * </p>
 */
public class IntegrityCheckerTest {

    /**
     * Prepares the test environment before each test method execution.
     * Resets the static integrity cache to ensure test isolation.
     *
     * @throws Exception If reflection fails to access or modify the field.
     */
    @Before
    public void setUp() throws Exception {
        // Reset the static cached field before each test
        resetIntegrityValidField();
    }

    /**
     * Cleans up the test environment after each test method execution.
     * Resets the static integrity cache.
     *
     * @throws Exception If reflection fails to access or modify the field.
     */
    @After
    public void tearDown() throws Exception {
        // Reset the static cached field after each test
        resetIntegrityValidField();
    }

    /**
     * Helper method to reset the internal {@code integrityValid} static cache via reflection.
     *
     * @throws Exception If reflection fails.
     */
    private void resetIntegrityValidField() throws Exception {
        Field field = IntegrityChecker.class.getDeclaredField("integrityValid");
        field.setAccessible(true);
        field.set(null, null);
    }


    /**
     * Tests the fast path of {@link IntegrityChecker#verifyIntegrity()} when
     * the result has already been cached as {@code true}.
     *
     * @throws Exception If reflection fails.
     */
    @Test
    public void testVerifyIntegrity_CachedTrue() throws Exception {
        // Force the cached value to true
        Field field = IntegrityChecker.class.getDeclaredField("integrityValid");
        field.setAccessible(true);
        field.set(null, true);

        // Should return true without evaluating the rest of the logic
        String result = IntegrityChecker.verifyIntegrity();
        assertNull("Integrity check should pass (return null) when hashes match", result);
    }

    /**
     * Tests the fast path of {@link IntegrityChecker#verifyIntegrity()} when
     * the result has already been cached as {@code false}.
     *
     * @throws Exception If reflection fails.
     */
    @Test
    public void testVerifyIntegrity_CachedFalse() throws Exception {
        // Force the cached value to false
        Field field = IntegrityChecker.class.getDeclaredField("integrityValid");
        field.setAccessible(true);
        field.set(null, false);

        // Should return false without evaluating the rest of the logic
        assertNotNull(IntegrityChecker.verifyIntegrity());
    }

    /**
     * Tests the full execution of {@link IntegrityChecker#verifyIntegrity()}
     * without bypassing the cache. Simulates standard test runner conditions.
     * <p>
     * When {@code integrity.properties} is absent from the test classpath
     * (which is the normal situation during unit tests — the file is only
     * generated by {@code atlas-package}) the XML/JS hash checks are skipped
     * and the outcome depends solely on the classloader name check.
     * </p>
     *
     * @throws Exception If reflection fails or underlying errors occur.
     */
    @Test
    public void testVerifyIntegrity_DefaultClassLoader() throws Exception {
        ClassLoader cl = IntegrityChecker.class.getClassLoader();
        String clName = cl.getClass().getName();

        // In a normal JUnit run the classloader is NOT an OSGi/Atlassian loader,
        // so verifyIntegrity() returns false after the classloader check.
        // If someone somehow runs tests inside an Atlassian container it may
        // return true — the assertion handles both cases.
        boolean classLoaderOk = clName.contains("atlassian") ||
                                clName.contains("plugin") ||
                                clName.contains("osgi") ||
                                clName.contains("felix");

        assertEquals(
            "verifyIntegrity() must match the classloader check outcome when " +
            "integrity.properties is absent from the classpath",
            classLoaderOk, IntegrityChecker.verifyIntegrity());
    }

    /**
     * Confirms that when {@code integrity.properties} is not present on the
     * test classpath (the normal state during unit tests), both expected hash
     * fields are {@code null} and the corresponding hash-skip path is taken.
     * <p>
     * This is verified indirectly: if the properties were accidentally bundled
     * with wrong hashes the test in {@link #testVerifyIntegrity_DefaultClassLoader}
     * would still pass, but the plugin would be permanently locked in production.
     * This test guards against that by asserting that hashes stored via the
     * properties file are only non-null when the file actually exists.
     * </p>
     */
    @Test
    public void testIntegrityProperties_AbsentFromTestClasspath() {
        // integrity.properties is generated by maven-antrun-plugin during atlas-package.
        // It must NOT exist on the test classpath so that unit tests are not accidentally
        // blocked by stale/wrong hashes.
        java.io.InputStream is = IntegrityChecker.class.getClassLoader()
                .getResourceAsStream("integrity.properties");
        // If this assertion fails it means a stale integrity.properties was accidentally
        // committed to src/test/resources — delete it and re-run.
        assertNull("integrity.properties must NOT be present on the unit-test classpath "
                + "(it is generated by the build, not committed to source)", is);
    }

    /**
     * Tests the private {@code verifyClassLoader} method specifically using reflection.
     *
     * @throws Exception If reflection fails.
     */
    @Test
    public void testVerifyClassLoader() throws Exception {
        Method method = IntegrityChecker.class.getDeclaredMethod("verifyClassLoader");
        method.setAccessible(true);

        ClassLoader cl = IntegrityChecker.class.getClassLoader();
        String clName = cl.getClass().getName();

        boolean expectedResult = clName.contains("atlassian") ||
                                 clName.contains("plugin") ||
                                 clName.contains("osgi") ||
                                 clName.contains("felix");

        boolean result = (boolean) method.invoke(null);
        assertEquals(expectedResult, result);
    }

    /**
     * Tests the SHA-256 resource hashing functionality using a known test file.
     * Verifies that the generated hash is not null, has a length of 64 characters,
     * and strictly matches the expected hash sum.
     */
    @Test
    public void testCalculateResourceHash_ValidResource() {
        String hash = IntegrityChecker.calculateResourceHash("test-resource.txt");
        assertNotNull("Hash should not be null for existing resource", hash);
        assertEquals("Hash should be 64 characters long", 64, hash.length());

        // Exact SHA-256 for the test resource
        assertEquals("6ae8a75555209fd6c44157c0aed8016e763ff435a19cf186f76863140143ff72", hash);
    }

    /**
     * Tests the resource hashing function against a non-existent file.
     * Verifies that it safely catches the exception and returns {@code null}
     * instead of propagating an error.
     */
    @Test
    public void testCalculateResourceHash_InvalidResource() {
        String hash = IntegrityChecker.calculateResourceHash("non-existent-resource.txt");
        assertNull("Hash should be null for non-existing resource", hash);
    }
}
